version: '3.8'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: lead_app:${version:-latest}
    container_name: lead_app
    depends_on:
      - database
    ports:
      - "5000:5000"
  database:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: local_postgres:${version:-latest}
    container_name: local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"