"""empty message

Revision ID: 438edd82c39b
Revises: c73b62eb1917
Create Date: 2023-10-09 20:06:22.655561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438edd82c39b'
down_revision = 'c73b62eb1917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ElementsToProcess',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idBulk', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ElementsToProcess')
    # ### end Alembic commands ###
